manifest:
  defaults:
    revision: encoder
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/DEREFERENC3D
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
